# Site settings
title: Gabriel Johnson
email: gdj@dainjae.com
description: > # this means to ignore newlines until "baseurl:"
  Find more about the person who will invent new substances
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dainjae.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
